### PR TITLE
Refine AI chatbot registration process

### LINKED ISSUE #10: Refine AI chatbot registration process
# Description

In the tests of the AI chatbot feature, we identified a few improvements to be made. The error messages need to be improved, so the users can read detailed information on what's not working.

### Improve error messages

Add as much information as possible in the error messages.

Image

### Rollback the registration process

After making a few failed attempts to register new models, the registration process should have rolled back the partially successful steps, but it didn't. We need to fix this.

Image

### PR DESCRIPTION
**Pull request by guidomodarelli**
# Description

This PR add error handling and backend consistency when a model registration fails.

1. **Validation of failed `Test Model Connection`**

   * Tests the flow of adding a model with an **invalid API Key**.
   * Ensures the connection step fails as expected.
   * Verifies that clicking the failed step’s cross now displays **detailed error information** (instead of just the status code).

2. **Rollback execution when model registration step fails**

   * Tests model registration with an **invalid API Key** to force a failure.
   * Validates that the UI shows a **rollback executed** message.
   * Confirms through **DevTools (Network tab)** that the correct backend rollback endpoints are triggered.

## Issue resolved

closes https://github.com/wazuh/wazuh-dashboard-ml-commons/issues/10

## Tasks/Evidence

- Verifies that clicking the failed step’s cross now displays detailed error information (instead of just the status code).
  
  <img width="1653" height="923" alt="image" src="https://github.com/user-attachments/assets/51a8d310-11c7-44a0-b26a-69ecf9f2eccb" />

- Enhance the error popover by adding a «panelStyle» property with word-wrapping. This ensures long text breaks properly, improving readability and preventing layout issues.
- Enhance error propagation and contextual data in HTTP client operations by introducing a detailed «HttpError» utility.
- Refactor installation steps to incorporate structured error handling using «StepError», providing detailed context and possible causes for failures. Improve diagnostic messaging during installation, including step-specific details and enriched error descriptions.
- Add utility functions to extract status codes and derive potential causes for issues, improving debugging capabilities.
- Introduce rollback functionality to the installation process, enabling the reversal of completed steps upon failure. Extend «InstallationAIAssistantStep» with a new «rollback» method and update «InstallationProgressManager» to manage rollback execution. Add rollback handling for agent, connector, and model creation steps, ensuring created resources are cleaned up if subsequent steps fail.
- Enhance the UI to display rollback summaries using «addInfoToast» when installation errors occur.
    <img width="1669" height="941" alt="image" src="https://github.com/user-attachments/assets/09f57418-3e5d-40cb-b346-fefa8f3de535" />

  - Introduce rollback tracking in the installation process to record reverted steps during failures.
  - Update the response structure to include a «rollbacks» field and propagate this data through the installation workflow.
  - Modify tests to verify rollback behavior and ensure accurate reporting of reverted steps.
  - Improve error handling and state management by adding a reference to track the last rollback summary and avoid duplicate toasts.

## Evidence

### 🟢 Test Legend

| Symbol | Meaning                                                              |
| ------ | -------------------------------------------------------------------- |
| ⚫      | The test hasn't started yet.                                         |
| 🟢     | All checks passed.                                                   |
| 🟡     | There is at least one expected fail or skipped test and no failures. |
| 🔴     | There is at least one failed check.                                  |
| ⚪      | Doesn't apply.                                                       |
| 🔧     | Request changes.                                                     |
| ❓      | Needs more information.                                              |

---

## 🧪 UI Tests

| Test Description                                                                                                                                                                                                                                                    | Chrome | Firefox | Safari |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------ | ------- | ------ |
| 1️⃣ In **Explore > Machine Learning**: Click **Add Model** → Fill required fields → Enter invalid **API Key** → Step **Test Model Connection** should fail → Clicking the failed step's cross should display **detailed error info (not just status code)**         | ⚫      | ⚫       | ⚫      |
| 2️⃣ In **Explore > Machine Learning**: Click **Add Model** → Fill required fields → Enter invalid **API Key** → Registration should fail → UI must show **rollback executed** message → In **DevTools > Network**, verify rollback endpoints were called in backend | ⚫      | ⚫       | ⚫      |

---

### 📋Test Details

<details><summary>⚫ 1️⃣ In **Explore > Machine Learning**: Click **Add Model** → Fill required fields → Enter invalid **API Key** → Step **Test Model Connection** should fail → Clicking the failed step's cross should display **detailed error info (not just status code)**</summary>
  <br />

> **CHROME** - ⚫

> **FIREFOX** - ⚫

> **SAFARI** - ⚫

</details>

<details><summary>⚫ 2️⃣ In **Explore > Machine Learning**: Click **Add Model** → Fill required fields → Enter invalid **API Key** → Registration should fail → UI must show **rollback executed** message → In **DevTools > Network**, verify rollback endpoints were called in backend</summary>
  <br />

> **CHROME** - ⚫

> **FIREFOX** - ⚫

> **SAFARI** - ⚫

</details>

### CODE REVIEW

**Comment by guidomodarelli** [comment]
All errors related to this specific linter rule will be ignored.

```
Error:   1:1  error  File must start with a license header  @osd/eslint/require-license-header
```

**Comment by gonzaarancibia** [comment]
### 🟢   Test Legend

| Symbol | Meaning                                                              |
| ------ | -------------------------------------------------------------------- |
| ⚫      | The test hasn't started yet.                                         |
| 🟢     | All checks passed.                                                   |
| 🟡     | There is at least one expected fail or skipped test and no failures. |
| 🔴     | There is at least one failed check.                                  |
| ⚪      | Doesn't apply.                                                       |
| 🔧     | Request changes.                                                     |
| ❓      | Needs more information.                                              |

---

## 🧪 UI Tests 🟢 

| Test Description                                                                                                                                                                                                                                                    | Chrome | Firefox | Safari |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------ | ------- | ------ |
| 1️⃣ In **Explore > Machine Learning**: Click **Add Model** → Fill required fields → Enter invalid **API Key** → Step **Test Model Connection** should fail → Clicking the failed step's cross should display **detailed error info (not just status code)**         | 🟢      | 🟢       | 🟢      |
| 2️⃣ In **Explore > Machine Learning**: Click **Add Model** → Fill required fields → Enter invalid **API Key** → Registration should fail → UI must show **rollback executed** message → In **DevTools > Network**, verify rollback endpoints were called in backend | 🟢       | 🟢        | 🟢       |

---

### 📋Test Details

<details><summary>🟢  1️⃣ In **Explore > Machine Learning**: Click **Add Model** → Fill required fields → Enter invalid **API Key** → Step **Test Model Connection** should fail → Clicking the failed step's cross should display **detailed error info (not just status code)**</summary>
  <br />

> **CHROME** - 🟢  
<img width="1256" height="854" alt="Screenshot 2025-09-22 at 7 28 48 AM" src="https://github.com/user-attachments/assets/34bfeb97-8b52-496b-accb-07781e4ad238" />

> **FIREFOX** - 🟢  
<img width="1768" height="901" alt="Screenshot 2025-09-22 at 7 36 11 AM" src="https://github.com/user-attachments/assets/18d0de0c-b2bf-4d13-bbd5-2b2fcb6e8832" />

> **SAFARI** - 🟢  
<img width="1792" height="843" alt="Screenshot 2025-09-22 at 7 37 22 AM" src="https://github.com/user-attachments/assets/78cf218c-00f6-4b94-84a5-a69cb38156f2" />

</details>

<details><summary> 🟢  2️⃣ In **Explore > Machine Learning**: Click **Add Model** → Fill required fields → Enter invalid **API Key** → Registration should fail → UI must show **rollback executed** message → In **DevTools > Network**, verify rollback endpoints were called in backend</summary>

  <br />

> **CHROME** - 🟢 
<img width="1911" height="996" alt="Screenshot 2025-09-22 at 7 41 13 AM" src="https://github.com/user-attachments/assets/183b69da-0e05-4d60-80be-281c795dfcfd" />



> **FIREFOX** - 🟢 
<img width="1779" height="1003" alt="Screenshot 2025-09-22 at 7 42 44 AM" src="https://github.com/user-attachments/assets/033d3ef8-8a4e-4719-a368-9212316d6828" />

> **SAFARI** - 🟢 
<img width="1789" height="983" alt="Screenshot 2025-09-22 at 7 41 47 AM" src="https://github.com/user-attachments/assets/76b12bc8-a32e-4563-9988-b1b985eeb76a" />

</details>

File: public/dashboard-assistant/modules/installation-manager/infrastructure/steps/update-ml-commons-settings-step.ts [hunk 1]
```diff
@@ -43,4 +58,12 @@ export class UpdateMlCommonsSettingsStep extends InstallationAIAssistantStep {
...
     return 'Failed to update ML Commons settings. Please check the configuration and try again.';
   }
+
+  public async rollback(
+    _request: InstallAIDashboardAssistantDto,
+    _context: InstallationContext,
+    _error: Error
+  ): Promise<void> {
+    // Current implementation does not persist auxiliary data to revert; nothing to rollback.
+  }
```
Comment (gonzaarancibia) [inline public/dashboard-assistant/modules/installation-manager/infrastructure/steps/update-ml-commons-settings-step.ts:68]: Is this necessary?

Comment (gonzaarancibia) [inline public/dashboard-assistant/modules/installation-manager/infrastructure/steps/update-ml-commons-settings-step.ts:68]: Is this necessary?

**Review by gonzaarancibia — APPROVED** [review]
🟢 LGTM

File: public/dashboard-assistant/modules/installation-manager/infrastructure/steps/update-ml-commons-settings-step.ts (hunk 1 above)
Comment (guidomodarelli) [reply public/dashboard-assistant/modules/installation-manager/infrastructure/steps/update-ml-commons-settings-step.ts:68]: I decided to leave this method explicitly to understand why it doesn't have any implementation.

**Comment by Machi3mfl** [comment]
## 🧪 UI Tests 🟢 

| Test Description                                                                                                                                                                                                                                                    | Chrome | Firefox | Safari |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------ | ------- | ------ |
| 1️⃣ In **Explore > Machine Learning**: Click **Add Model** → Fill required fields → Enter invalid **API Key** → Step **Test Model Connection** should fail → Clicking the failed step's cross should display **detailed error info (not just status code)**         | 🟢      | ⚪        | ⚪      |
| 2️⃣ In **Explore > Machine Learning**: Click **Add Model** → Fill required fields → Enter invalid **API Key** → Registration should fail → UI must show **rollback executed** message → In **DevTools > Network**, verify rollback endpoints were called in backend | 🟢      | ⚪       | ⚪      |

---

### 📋Test Details

<details><summary>🟢 1️⃣ In **Explore > Machine Learning**: Click **Add Model** → Fill required fields → Enter invalid **API Key** → Step **Test Model Connection** should fail → Clicking the failed step's cross should display **detailed error info (not just status code)**</summary>
  <br />

> **CHROME** - 🟢


https://github.com/user-attachments/assets/ed64d3ce-874e-4dcc-9e1c-52ead85377fb



> **FIREFOX** - ⚪

> **SAFARI** - ⚪

</details>

<details><summary>🟢 2️⃣ In **Explore > Machine Learning**: Click **Add Model** → Fill required fields → Enter invalid **API Key** → Registration should fail → UI must show **rollback executed** message → In **DevTools > Network**, verify rollback endpoints were called in backend</summary>
  <br />

> **CHROME** - 🟢


https://github.com/user-attachments/assets/29776e3b-c20a-4615-acf6-2c9bd6cba95d



> **FIREFOX** - ⚪

> **SAFARI** - ⚪

</details>

**Review by Machi3mfl — APPROVED** [review]
LGTM!
